# Generated by Django 4.1.4 on 2022-12-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название новости')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('date_pub', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
    ]
